[[constraint]]
  name = "github.com/Financial-Times/api-endpoint"
  version = "0.0.2"

[[constraint]]
  name = "github.com/Financial-Times/go-ft-http"
  version = "0.0.3"

[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.4.0"

[[constraint]]
  name = "github.com/Financial-Times/http-handlers-go"
  version = "0.1.1"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/Financial-Times/transactionid-utils-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/husobee/vestigo"
  version = "1.0.2"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[prune]
  go-tests = true
  unused-packages = true
