# Values used for the deployed application.
replicaCount: 2

eksCluster: true

service:
  name: draft-annotations-api

encryptedSecrets:
  upp-api-key: AgCAJCRlyeXjjWs8RTpfUh5hN70rxYXqmbpNV0LTu5LPt31FNWxbcykAR9TUinh7PAFMTC+piSTVq8fwgznKjooN5D+4szI52RQH35stwmWheMlS+0NO7eoiZ0N+I+85WZ/cYGu6P5GfDyB6ydEyrLEC34I9WplvoCaB6ldVHp1BsWrooCZYupKaZbp0dHgLaleflteEX35kdaChF7GbmkOIebSWIPXk4f4DW9SXKv7d/lQbBN1gFLH2V00CJcqMdPQuCE+rDPsy9aCOERLyuYvOIOOyGn7zgw3A/e6FWoRsIeG6goTSRNP+WGZz+fLYENVzS1f+fCePkc13tHV8lp0OZLmx86RWyr74/P+mB+vjhd7UiBYUfSTTz9aT7628qBThLSvbMvzs4UltQPTgKtxG5QtqY2vLB5QSsx/kRWvyXduZcmrs+xkg63DaVTAJxSJzuT1QWrh0AwNk3F6sIFBBPJOrInHUJRLlz756dG7iv143nZOcrtIwdhDtriBCnfi4LuvMBg9v+CpehPhdd1AHzZQVBop75xzCue9hcmEo6/zaw3/FNV5f3lGLUthEXemYHdawjTnSAS8dFzNJXVTFJpWPOFn3mZYPn+0lJ6sQmcpPTJBhjy/0FmRlwoebY/X5n8ge3TxS4xvfw0TXorg2xBjGEfuprvIM3h1wV/UlY7btl8fDpbWuEOezUIO46uZun4my7zGMhFvsVLvdoWIUbdFuUctBI/uLZPvurm05xOmNjzjLfmTlgGVcnd9+vbt+SorxSD/YFQ==
