apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ANNOTATIONS_RW_ENDPOINT
          value: "http://generic-rw-aurora:8080"
        - name: ANNOTATIONS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: annotations-endpoint
        - name: HTTP_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: timeout-config
              key: draft-annotations-api-timeout
        - name: INTERNAL_CONCORDANCES_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: internal-concordances-endpoint
        - name: UPP_APIKEY
          valueFrom:
            secretKeyRef:
              name: draft-annotations-api
              key: upp-api-key
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
