apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: draft-annotations-api
  namespace: default
spec:
  encryptedData:
{{ if .Values.encryptedSecrets }}{{ toYaml .Values.encryptedSecrets | indent 4 }}{{ end }}
